//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordToTFS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordToTFS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddDetails_Add_Label {
            get {
                return ResourceManager.GetString("AddDetails_Add_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Details as.
        /// </summary>
        public static string AddDetails_As_Label {
            get {
                return ResourceManager.GetString("AddDetails_As_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Work Item ID.
        /// </summary>
        public static string AddDetails_By_Work_Item_ID_Tab {
            get {
                return ResourceManager.GetString("AddDetails_By_Work_Item_ID_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddDetails_Cancel_Label {
            get {
                return ResourceManager.GetString("AddDetails_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Work Item.
        /// </summary>
        public static string AddDetails_Choose_Work_Item_Label {
            get {
                return ResourceManager.GetString("AddDetails_Choose_Work_Item_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        public static string AddDetails_Current_Document_Tab {
            get {
                return ResourceManager.GetString("AddDetails_Current_Document_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Work Items by Type.
        /// </summary>
        public static string AddDetails_Filter_Work_Items_By_Type_Label {
            get {
                return ResourceManager.GetString("AddDetails_Filter_Work_Items_By_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string AddDetails_Replace_Label {
            get {
                return ResourceManager.GetString("AddDetails_Replace_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add details to work item.
        /// </summary>
        public static string AddDetails_Title {
            get {
                return ResourceManager.GetString("AddDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item ID.
        /// </summary>
        public static string AddDetails_Work_Item_ID {
            get {
                return ResourceManager.GetString("AddDetails_Work_Item_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Connect_Cancel_Label {
            get {
                return ResourceManager.GetString("Connect_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Connect_Login_Label {
            get {
                return ResourceManager.GetString("Connect_Login_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Connect_Password_Label {
            get {
                return ResourceManager.GetString("Connect_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect_Title {
            get {
                return ResourceManager.GetString("Connect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Connect_User_Name_Label {
            get {
                return ResourceManager.GetString("Connect_User_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateNew_Cancel_Label {
            get {
                return ResourceManager.GetString("CreateNew_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateNew_Create_Label {
            get {
                return ResourceManager.GetString("CreateNew_Create_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new work item.
        /// </summary>
        public static string CreateNew_Title {
            get {
                return ResourceManager.GetString("CreateNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CreateNew_Title_Label {
            get {
                return ResourceManager.GetString("CreateNew_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Type.
        /// </summary>
        public static string CreateNew_Work_Item_Type_Label {
            get {
                return ResourceManager.GetString("CreateNew_Work_Item_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        public static string DatePickerWatermark {
            get {
                return ResourceManager.GetString("DatePickerWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create work item. Item contain required &apos;{0}&apos; field that have to be filled..
        /// </summary>
        public static string ERROR_MESSAGE_UNABLE_TO_CREATE_ITEM_WITH_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE_UNABLE_TO_CREATE_ITEM_WITH_REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ErrorDialog_Ok_Button {
            get {
                return ResourceManager.GetString("ErrorDialog_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ExportDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("ExportDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALMA is going to accept all tracking changes in this document. Do you wish to proceed?.
        /// </summary>
        public static string ExportDialog_Message {
            get {
                return ResourceManager.GetString("ExportDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ExportDialog_Ok_Button {
            get {
                return ResourceManager.GetString("ExportDialog_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALMA – Accept All Changes.
        /// </summary>
        public static string ExportDialog_Title {
            get {
                return ResourceManager.GetString("ExportDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ImportDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("ImportDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportDialog_Import_Button {
            get {
                return ResourceManager.GetString("ImportDialog_Import_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import work items.
        /// </summary>
        public static string ImportDialog_Title {
            get {
                return ResourceManager.GetString("ImportDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create control for empty description.
        /// </summary>
        public static string ImporteDialog_CheckBox {
            get {
                return ResourceManager.GetString("ImporteDialog_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format corrupted.
        /// </summary>
        public static string lblFormatCorruptedLabel {
            get {
                return ResourceManager.GetString("lblFormatCorruptedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LinkItem_Cancel_Label {
            get {
                return ResourceManager.GetString("LinkItem_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Work Item.
        /// </summary>
        public static string LinkItem_Choose_Work_Item {
            get {
                return ResourceManager.GetString("LinkItem_Choose_Work_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string LinkItem_Comments {
            get {
                return ResourceManager.GetString("LinkItem_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        public static string LinkItem_Existing_Document {
            get {
                return ResourceManager.GetString("LinkItem_Existing_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Work Items by Type.
        /// </summary>
        public static string LinkItem_Filter_Work_Items_By_Type_Label {
            get {
                return ResourceManager.GetString("LinkItem_Filter_Work_Items_By_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        public static string LinkItem_HyperLink {
            get {
                return ResourceManager.GetString("LinkItem_HyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        public static string LinkItem_Hyperlink_LABEL {
            get {
                return ResourceManager.GetString("LinkItem_Hyperlink_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Item as.
        /// </summary>
        public static string LinkItem_Link_Item_As {
            get {
                return ResourceManager.GetString("LinkItem_Link_Item_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Item.
        /// </summary>
        public static string LinkItem_LinkItem_Label {
            get {
                return ResourceManager.GetString("LinkItem_LinkItem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside Document.
        /// </summary>
        public static string LinkItem_Outside_Document {
            get {
                return ResourceManager.GetString("LinkItem_Outside_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link item to.
        /// </summary>
        public static string LinkItem_Title {
            get {
                return ResourceManager.GetString("LinkItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item IDs.
        /// </summary>
        public static string LinkItem_Work_Item_IDs {
            get {
                return ResourceManager.GetString("LinkItem_Work_Item_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Type.
        /// </summary>
        public static string LinkItem_Work_Item_Type {
            get {
                return ResourceManager.GetString("LinkItem_Work_Item_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MatrixReport_Cancel {
            get {
                return ResourceManager.GetString("MatrixReport_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string MatrixReport_Columns {
            get {
                return ResourceManager.GetString("MatrixReport_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string MatrixReport_Created_Date {
            get {
                return ResourceManager.GetString("MatrixReport_Created_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MatrixReport_Date {
            get {
                return ResourceManager.GetString("MatrixReport_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        public static string MatrixReport_Date_From {
            get {
                return ResourceManager.GetString("MatrixReport_Date_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        public static string MatrixReport_Date_To {
            get {
                return ResourceManager.GetString("MatrixReport_Date_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string MatrixReport_From {
            get {
                return ResourceManager.GetString("MatrixReport_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include not linked Items.
        /// </summary>
        public static string MatrixReport_Include_Not_Linked_Items {
            get {
                return ResourceManager.GetString("MatrixReport_Include_Not_Linked_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string MatrixReport_Insert {
            get {
                return ResourceManager.GetString("MatrixReport_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type.
        /// </summary>
        public static string MatrixReport_Link_Type {
            get {
                return ResourceManager.GetString("MatrixReport_Link_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string MatrixReport_Rows {
            get {
                return ResourceManager.GetString("MatrixReport_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string MatrixReport_State {
            get {
                return ResourceManager.GetString("MatrixReport_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix report.
        /// </summary>
        public static string MatrixReport_Title {
            get {
                return ResourceManager.GetString("MatrixReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string MatrixReport_To {
            get {
                return ResourceManager.GetString("MatrixReport_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following required fields will be filled with default values:.
        /// </summary>
        public static string MESSAGE_ITEMS_WITH_DEFAULT_FIELDS {
            get {
                return ResourceManager.GetString("MESSAGE_ITEMS_WITH_DEFAULT_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Obolete_List_Item_Copy {
            get {
                return ResourceManager.GetString("Obolete_List_Item_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Obolete_List_Item_Move {
            get {
                return ResourceManager.GetString("Obolete_List_Item_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Obsolete_List_Action_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Obsolete_List_WIId_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_WIId_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link End.
        /// </summary>
        public static string Obsolete_List_WILink_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_WILink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Obsolete_List_WITitle_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_WITitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Type.
        /// </summary>
        public static string Obsolete_List_WIType_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_WIType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ObsoleteWorkItem_Cancel_Lablel {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Cancel_Lablel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete Work Item label.
        /// </summary>
        public static string ObsoleteWorkItem_Label_Item {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Label_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string ObsoleteWorkItem_Label_Links {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Label_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ObsoleteWorkItem_Ok_Label {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Ok_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Tags.
        /// </summary>
        public static string ObsoleteWorkItem_Tag_Item {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Tag_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Work Item.
        /// </summary>
        public static string ObsoleteWorkItem_Title {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Title.
        /// </summary>
        public static string ObsoleteWorkItem_Title_Item {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Title_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Progress_Stop {
            get {
                return ResourceManager.GetString("Progress_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Text.
        /// </summary>
        public static string QueryReport_Body_Text {
            get {
                return ResourceManager.GetString("QueryReport_Body_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Queries.
        /// </summary>
        public static string QueryReport_By_Queries_Tab {
            get {
                return ResourceManager.GetString("QueryReport_By_Queries_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Work Item IDs.
        /// </summary>
        public static string QueryReport_By_WI_ID_Tab {
            get {
                return ResourceManager.GetString("QueryReport_By_WI_ID_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string QueryReport_Cancel {
            get {
                return ResourceManager.GetString("QueryReport_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string QueryReport_Header {
            get {
                return ResourceManager.GetString("QueryReport_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Attachments.
        /// </summary>
        public static string QueryReport_Include_Attachments {
            get {
                return ResourceManager.GetString("QueryReport_Include_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string QueryReport_Insert {
            get {
                return ResourceManager.GetString("QueryReport_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Queries.
        /// </summary>
        public static string QueryReport_List_Of_Queries {
            get {
                return ResourceManager.GetString("QueryReport_List_Of_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Queries.
        /// </summary>
        public static string QueryReport_Manage_Queries {
            get {
                return ResourceManager.GetString("QueryReport_Manage_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string QueryReport_Metadata {
            get {
                return ResourceManager.GetString("QueryReport_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can type multiple WI, separated by commas..
        /// </summary>
        public static string QueryReport_Multiple_WI {
            get {
                return ResourceManager.GetString("QueryReport_Multiple_WI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Work items that don&apos;t belong to the current project will not be included to the report..
        /// </summary>
        public static string QueryReport_Not_In_Current_Document_Message {
            get {
                return ResourceManager.GetString("QueryReport_Not_In_Current_Document_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Format.
        /// </summary>
        public static string QueryReport_Report_Format {
            get {
                return ResourceManager.GetString("QueryReport_Report_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Date.
        /// </summary>
        public static string QueryReport_RevisionDate_Text {
            get {
                return ResourceManager.GetString("QueryReport_RevisionDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string QueryReport_Title {
            get {
                return ResourceManager.GetString("QueryReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Items IDs.
        /// </summary>
        public static string QueryReport_Work_Items_ID {
            get {
                return ResourceManager.GetString("QueryReport_Work_Items_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string RequiredFields_Fields_plural {
            get {
                return ResourceManager.GetString("RequiredFields_Fields_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string RequiredFields_Fields_singular {
            get {
                return ResourceManager.GetString("RequiredFields_Fields_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must contain numeric value.
        /// </summary>
        public static string RequiredFields_Must_Contain_Numeric_Value_plural {
            get {
                return ResourceManager.GetString("RequiredFields_Must_Contain_Numeric_Value_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must contain numeric value.
        /// </summary>
        public static string RequiredFields_Must_Contain_Numeric_Value_singular {
            get {
                return ResourceManager.GetString("RequiredFields_Must_Contain_Numeric_Value_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are required.
        /// </summary>
        public static string RequiredFields_Required_plural {
            get {
                return ResourceManager.GetString("RequiredFields_Required_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        public static string RequiredFields_Required_singular {
            get {
                return ResourceManager.GetString("RequiredFields_Required_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See attachments.
        /// </summary>
        public static string SeeAttachments_Text {
            get {
                return ResourceManager.GetString("SeeAttachments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string StepActionsResult_Action_Label {
            get {
                return ResourceManager.GetString("StepActionsResult_Action_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string StepActionsResult_Add_Button {
            get {
                return ResourceManager.GetString("StepActionsResult_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StepActionsResult_Cancel_Button {
            get {
                return ResourceManager.GetString("StepActionsResult_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Result.
        /// </summary>
        public static string StepActionsResult_Expected_Result_Label {
            get {
                return ResourceManager.GetString("StepActionsResult_Expected_Result_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Step.
        /// </summary>
        public static string StepActionsResult_Title {
            get {
                return ResourceManager.GetString("StepActionsResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string UpdateDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("UpdateDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import content.
        /// </summary>
        public static string UpdateDialog_CheckBox {
            get {
                return ResourceManager.GetString("UpdateDialog_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALMA is going to accept all tracking changes in this document. Do you wish to proceed?.
        /// </summary>
        public static string UpdateDialog_Message {
            get {
                return ResourceManager.GetString("UpdateDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string UpdateDialog_Ok_Button {
            get {
                return ResourceManager.GetString("UpdateDialog_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALMA – Accept All Changes.
        /// </summary>
        public static string UpdateDialog_Title {
            get {
                return ResourceManager.GetString("UpdateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordSectionGroup/Word2007Section.
        /// </summary>
        public static string Word2007Section {
            get {
                return ResourceManager.GetString("Word2007Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordSectionGroup/WordSection.
        /// </summary>
        public static string WordSection {
            get {
                return ResourceManager.GetString("WordSection", resourceCulture);
            }
        }
    }
}
