//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salma2010.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salma2010.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string btnActivateLabel {
            get {
                return ResourceManager.GetString("btnActivateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Details.
        /// </summary>
        internal static string btnAddDetailsLabel {
            get {
                return ResourceManager.GetString("btnAddDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add work item details.
        /// </summary>
        internal static string btnAddDetailsToolTip {
            get {
                return ResourceManager.GetString("btnAddDetailsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string btnCollapseWorkItemLabel {
            get {
                return ResourceManager.GetString("btnCollapseWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from TFS.
        /// </summary>
        internal static string btnConnect_disconnectToolTip {
            get {
                return ResourceManager.GetString("btnConnect_disconnectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string btnConnectLabel {
            get {
                return ResourceManager.GetString("btnConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to TFS.
        /// </summary>
        internal static string btnConnectToolTip {
            get {
                return ResourceManager.GetString("btnConnectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string btnDisconnectLabel {
            get {
                return ResourceManager.GetString("btnDisconnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string btnExpandWorkItemLabel {
            get {
                return ResourceManager.GetString("btnExpandWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Item.
        /// </summary>
        internal static string btnExportItemLabel {
            get {
                return ResourceManager.GetString("btnExportItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export work item.
        /// </summary>
        internal static string btnExportItemToolTip {
            get {
                return ResourceManager.GetString("btnExportItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string btnHelp_mnuLabel {
            get {
                return ResourceManager.GetString("btnHelp_mnuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string btnHelpLabel {
            get {
                return ResourceManager.GetString("btnHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View help or activate SALMA.
        /// </summary>
        internal static string btnHelpToolTip {
            get {
                return ResourceManager.GetString("btnHelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Items.
        /// </summary>
        internal static string btnImportItemsLabel {
            get {
                return ResourceManager.GetString("btnImportItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import work items.
        /// </summary>
        internal static string btnImportItemsToolTip {
            get {
                return ResourceManager.GetString("btnImportItemsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Items.
        /// </summary>
        internal static string btnLinkItemsLabel {
            get {
                return ResourceManager.GetString("btnLinkItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link work items to internal or external resource.
        /// </summary>
        internal static string btnLinkItemsToolTip {
            get {
                return ResourceManager.GetString("btnLinkItemsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traceability Matrix.
        /// </summary>
        internal static string btnMatrixLabel {
            get {
                return ResourceManager.GetString("btnMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate traceability matrix containing TFS data.
        /// </summary>
        internal static string btnMatrixToolTip {
            get {
                return ResourceManager.GetString("btnMatrixToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string btnNewWorkItemLabel {
            get {
                return ResourceManager.GetString("btnNewWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new work item.
        /// </summary>
        internal static string btnNewWorkItemToolTip {
            get {
                return ResourceManager.GetString("btnNewWorkItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete Work Item.
        /// </summary>
        internal static string btnObsoleteWorkItemLabel {
            get {
                return ResourceManager.GetString("btnObsoleteWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Item.
        /// </summary>
        internal static string btnOpenWorkItemLabel {
            get {
                return ResourceManager.GetString("btnOpenWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open work item.
        /// </summary>
        internal static string btnOpenWorkItemToolTip {
            get {
                return ResourceManager.GetString("btnOpenWorkItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        internal static string btnReportLabel {
            get {
                return ResourceManager.GetString("btnReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate TFS report based on existing queries.
        /// </summary>
        internal static string btnReportToolTip {
            get {
                return ResourceManager.GetString("btnReportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string btnSettingsLabel {
            get {
                return ResourceManager.GetString("btnSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Panel.
        /// </summary>
        internal static string btnShowPanelLabel {
            get {
                return ResourceManager.GetString("btnShowPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comments.
        /// </summary>
        internal static string btnShowWorkItemsLabel {
            get {
                return ResourceManager.GetString("btnShowWorkItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide comments with TFS data.
        /// </summary>
        internal static string btnShowWorkItemsToolTip {
            get {
                return ResourceManager.GetString("btnShowWorkItemsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch TFS Account.
        /// </summary>
        internal static string btnSwitchTfsUserLabel {
            get {
                return ResourceManager.GetString("btnSwitchTfsUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch TFS user.
        /// </summary>
        internal static string btnSwitchTfsUserToolTip {
            get {
                return ResourceManager.GetString("btnSwitchTfsUserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Items.
        /// </summary>
        internal static string btnUpdateAndSyncLabel {
            get {
                return ResourceManager.GetString("btnUpdateAndSyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing work item status and content at document.
        /// </summary>
        internal static string btnUpdateAndSyncToolTip {
            get {
                return ResourceManager.GetString("btnUpdateAndSyncToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import content.
        /// </summary>
        internal static string btnUpdateLabel {
            get {
                return ResourceManager.GetString("btnUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing work item status at document.
        /// </summary>
        internal static string btnUpdateToolTip {
            get {
                return ResourceManager.GetString("btnUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter connection URL.
        /// </summary>
        internal static string connectionBoxToolTip {
            get {
                return ResourceManager.GetString("connectionBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Path.
        /// </summary>
        internal static string ddlAreasLabel {
            get {
                return ResourceManager.GetString("ddlAreasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type.
        /// </summary>
        internal static string ddlLinksLabel {
            get {
                return ResourceManager.GetString("ddlLinksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPC List.
        /// </summary>
        internal static string ddlProjectCollectionLabel {
            get {
                return ResourceManager.GetString("ddlProjectCollectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select team project collection.
        /// </summary>
        internal static string ddlProjectCollectionToolTip {
            get {
                return ResourceManager.GetString("ddlProjectCollectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string ddlProjectsLabel {
            get {
                return ResourceManager.GetString("ddlProjectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select team project.
        /// </summary>
        internal static string ddlProjectsToolTip {
            get {
                return ResourceManager.GetString("ddlProjectsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string edbLinkWiIDLabel {
            get {
                return ResourceManager.GetString("edbLinkWiIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item.
        /// </summary>
        internal static string edbLinkWiLabel {
            get {
                return ResourceManager.GetString("edbLinkWiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string group1Label {
            get {
                return ResourceManager.GetString("group1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string group2Label {
            get {
                return ResourceManager.GetString("group2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Items.
        /// </summary>
        internal static string group3Label {
            get {
                return ResourceManager.GetString("group3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to TFS.
        /// </summary>
        internal static string groupConnectLabel {
            get {
                return ResourceManager.GetString("groupConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Link.
        /// </summary>
        internal static string groupDefaultsLabel {
            get {
                return ResourceManager.GetString("groupDefaultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string groupHelpLabel {
            get {
                return ResourceManager.GetString("groupHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Items.
        /// </summary>
        internal static string groupManageWILabel {
            get {
                return ResourceManager.GetString("groupManageWILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string groupReportingLabel {
            get {
                return ResourceManager.GetString("groupReportingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALMA – Accept All Changes required.
        /// </summary>
        internal static string lblAcceptAllChangesRequiredCaptionLabel {
            get {
                return ResourceManager.GetString("lblAcceptAllChangesRequiredCaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALMA is going to accept all tracking changes in this document. Do you wish to proceed?.
        /// </summary>
        internal static string lblAcceptAllChangesRequiredLabel {
            get {
                return ResourceManager.GetString("lblAcceptAllChangesRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to add data.
        /// </summary>
        internal static string lblAddReplaceWorkItemErrorLabel {
            get {
                return ResourceManager.GetString("lblAddReplaceWorkItemErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item cannot be updated in the control {0}.
        /// </summary>
        internal static string lblApplyWorkItemErrorLabel {
            get {
                return ResourceManager.GetString("lblApplyWorkItemErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection URL.
        /// </summary>
        internal static string lblConnectionUrlLabel {
            get {
                return ResourceManager.GetString("lblConnectionUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control is not connected with work item.
        /// </summary>
        internal static string lblOpenWorkItemErrorLabel {
            get {
                return ResourceManager.GetString("lblOpenWorkItemErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work items.
        /// </summary>
        internal static string lblTaskPaneLabel {
            get {
                return ResourceManager.GetString("lblTaskPaneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        internal static string lblTextNotLoggedIn {
            get {
                return ResourceManager.GetString("lblTextNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        internal static string menuTfsUserLabel {
            get {
                return ResourceManager.GetString("menuTfsUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display current TFS user.
        /// </summary>
        internal static string menuTfsUserToolTip {
            get {
                return ResourceManager.GetString("menuTfsUserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string showWorkItems_hideLabel {
            get {
                return ResourceManager.GetString("showWorkItems_hideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comments.
        /// </summary>
        internal static string showWorkItemsLabel {
            get {
                return ResourceManager.GetString("showWorkItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string splitBtnConnect_connectedLabel {
            get {
                return ResourceManager.GetString("splitBtnConnect_connectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string splitBtnConnectLabel {
            get {
                return ResourceManager.GetString("splitBtnConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as: .
        /// </summary>
        internal static string statusLabel_loggedInLabel {
            get {
                return ResourceManager.GetString("statusLabel_loggedInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add work item details.
        /// </summary>
        internal static string TIP_ADD_WORK_ITEM_DETAILS {
            get {
                return ResourceManager.GetString("TIP_ADD_WORK_ITEM_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to TFS.
        /// </summary>
        internal static string TIP_CONNECT_TO_TFS {
            get {
                return ResourceManager.GetString("TIP_CONNECT_TO_TFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new work item.
        /// </summary>
        internal static string TIP_CREATE_NEW_WORK_ITEM {
            get {
                return ResourceManager.GetString("TIP_CREATE_NEW_WORK_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from TFS.
        /// </summary>
        internal static string TIP_DISCONNECT_FROM_TFS {
            get {
                return ResourceManager.GetString("TIP_DISCONNECT_FROM_TFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter connection URL.
        /// </summary>
        internal static string TIP_ENTER_CONNECTION_URL {
            get {
                return ResourceManager.GetString("TIP_ENTER_CONNECTION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate traceability matrix containing TFS data.
        /// </summary>
        internal static string TIP_GENERATE_MATRIX_BUTTON {
            get {
                return ResourceManager.GetString("TIP_GENERATE_MATRIX_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate TFS report based on existing queries.
        /// </summary>
        internal static string TIP_GENERATE_REPORT_BUTTON {
            get {
                return ResourceManager.GetString("TIP_GENERATE_REPORT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View help or activate SALMA.
        /// </summary>
        internal static string TIP_HELP_BUTTON {
            get {
                return ResourceManager.GetString("TIP_HELP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link work items to internal or external resources.
        /// </summary>
        internal static string TIP_LINK_WORK_ITEMS {
            get {
                return ResourceManager.GetString("TIP_LINK_WORK_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select team project.
        /// </summary>
        internal static string TIP_SELECT_TEAM_PROJECT {
            get {
                return ResourceManager.GetString("TIP_SELECT_TEAM_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select team project collection.
        /// </summary>
        internal static string TIP_SELECT_TEAM_PROJECT_COLLECTION {
            get {
                return ResourceManager.GetString("TIP_SELECT_TEAM_PROJECT_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide comments with TFS data.
        /// </summary>
        internal static string TIP_SHOW_HIDE_COMMENTS {
            get {
                return ResourceManager.GetString("TIP_SHOW_HIDE_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update work item information from TFS.
        /// </summary>
        internal static string TIP_UPDATE_BUTTON {
            get {
                return ResourceManager.GetString("TIP_UPDATE_BUTTON", resourceCulture);
            }
        }
    }
}
