//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordToTFS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordToTFS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddDetails_Add_Label {
            get {
                return ResourceManager.GetString("AddDetails_Add_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add details as.
        /// </summary>
        public static string AddDetails_As_Label {
            get {
                return ResourceManager.GetString("AddDetails_As_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddDetails_Cancel_Label {
            get {
                return ResourceManager.GetString("AddDetails_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Work Item:.
        /// </summary>
        public static string AddDetails_Choose_Work_Item_Label {
            get {
                return ResourceManager.GetString("AddDetails_Choose_Work_Item_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter work items by type.
        /// </summary>
        public static string AddDetails_Filter_Work_Items_By_Type_Label {
            get {
                return ResourceManager.GetString("AddDetails_Filter_Work_Items_By_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string AddDetails_Replace_Label {
            get {
                return ResourceManager.GetString("AddDetails_Replace_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add details to work item.
        /// </summary>
        public static string AddDetails_Title {
            get {
                return ResourceManager.GetString("AddDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Connect_Cancel_Label {
            get {
                return ResourceManager.GetString("Connect_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Connect_Login_Label {
            get {
                return ResourceManager.GetString("Connect_Login_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Connect_Password_Label {
            get {
                return ResourceManager.GetString("Connect_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect_Title {
            get {
                return ResourceManager.GetString("Connect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Connect_User_Name_Label {
            get {
                return ResourceManager.GetString("Connect_User_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CreateNew_Cancel_Label {
            get {
                return ResourceManager.GetString("CreateNew_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateNew_Create_Label {
            get {
                return ResourceManager.GetString("CreateNew_Create_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new work item.
        /// </summary>
        public static string CreateNew_Title {
            get {
                return ResourceManager.GetString("CreateNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string CreateNew_Title_Label {
            get {
                return ResourceManager.GetString("CreateNew_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Type:.
        /// </summary>
        public static string CreateNew_Work_Item_Type_Label {
            get {
                return ResourceManager.GetString("CreateNew_Work_Item_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        public static string DatePickerWatermark {
            get {
                return ResourceManager.GetString("DatePickerWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LinkItem_Cancel_Label {
            get {
                return ResourceManager.GetString("LinkItem_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        public static string LinkItem_Comments {
            get {
                return ResourceManager.GetString("LinkItem_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Document.
        /// </summary>
        public static string LinkItem_Existing_Document {
            get {
                return ResourceManager.GetString("LinkItem_Existing_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter work items by type.
        /// </summary>
        public static string LinkItem_Filter_Work_Items_By_Type_Label {
            get {
                return ResourceManager.GetString("LinkItem_Filter_Work_Items_By_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        public static string LinkItem_HyperLink {
            get {
                return ResourceManager.GetString("LinkItem_HyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Item as:.
        /// </summary>
        public static string LinkItem_Link_Item_As {
            get {
                return ResourceManager.GetString("LinkItem_Link_Item_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Item.
        /// </summary>
        public static string LinkItem_LinkItem_Label {
            get {
                return ResourceManager.GetString("LinkItem_LinkItem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside Document.
        /// </summary>
        public static string LinkItem_Outside_Document {
            get {
                return ResourceManager.GetString("LinkItem_Outside_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Item to.
        /// </summary>
        public static string LinkItem_Title {
            get {
                return ResourceManager.GetString("LinkItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item ID&apos;s:.
        /// </summary>
        public static string LinkItem_Work_Item_IDs {
            get {
                return ResourceManager.GetString("LinkItem_Work_Item_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item Type:.
        /// </summary>
        public static string LinkItem_Work_Item_Type {
            get {
                return ResourceManager.GetString("LinkItem_Work_Item_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MatrixReport_Cancel {
            get {
                return ResourceManager.GetString("MatrixReport_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string MatrixReport_Columns {
            get {
                return ResourceManager.GetString("MatrixReport_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string MatrixReport_Created_Date {
            get {
                return ResourceManager.GetString("MatrixReport_Created_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string MatrixReport_From {
            get {
                return ResourceManager.GetString("MatrixReport_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include not linked items.
        /// </summary>
        public static string MatrixReport_Include_Not_Linked_Items {
            get {
                return ResourceManager.GetString("MatrixReport_Include_Not_Linked_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string MatrixReport_Insert {
            get {
                return ResourceManager.GetString("MatrixReport_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type.
        /// </summary>
        public static string MatrixReport_Link_Type {
            get {
                return ResourceManager.GetString("MatrixReport_Link_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string MatrixReport_Rows {
            get {
                return ResourceManager.GetString("MatrixReport_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string MatrixReport_State {
            get {
                return ResourceManager.GetString("MatrixReport_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix Report.
        /// </summary>
        public static string MatrixReport_Title {
            get {
                return ResourceManager.GetString("MatrixReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string MatrixReport_To {
            get {
                return ResourceManager.GetString("MatrixReport_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Progress_Stop {
            get {
                return ResourceManager.GetString("Progress_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Text.
        /// </summary>
        public static string QueryReport_Body_Text {
            get {
                return ResourceManager.GetString("QueryReport_Body_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string QueryReport_Cancel {
            get {
                return ResourceManager.GetString("QueryReport_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string QueryReport_Header {
            get {
                return ResourceManager.GetString("QueryReport_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Attachments.
        /// </summary>
        public static string QueryReport_Include_Attachments {
            get {
                return ResourceManager.GetString("QueryReport_Include_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string QueryReport_Insert {
            get {
                return ResourceManager.GetString("QueryReport_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Queries.
        /// </summary>
        public static string QueryReport_List_Of_Queries {
            get {
                return ResourceManager.GetString("QueryReport_List_Of_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Queries.
        /// </summary>
        public static string QueryReport_Manage_Queries {
            get {
                return ResourceManager.GetString("QueryReport_Manage_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string QueryReport_Metadata {
            get {
                return ResourceManager.GetString("QueryReport_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Format.
        /// </summary>
        public static string QueryReport_Report_Format {
            get {
                return ResourceManager.GetString("QueryReport_Report_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Report.
        /// </summary>
        public static string QueryReport_Title {
            get {
                return ResourceManager.GetString("QueryReport_Title", resourceCulture);
            }
        }

    }
}
